title: World of Melneri
description: A comprehensive reference for the mystical world of Melneri
baseurl: "/Melneri"
url: "https://lost-rabbit-digital.github.io/Melneri/"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Show downloads
show_downloads: false

# Theme overrides
github:
  is_project_page: false